version: '2.13'

services:
  api:
    build:
      context: .

      dockerfile: dockerfile

    ports:
      - "3000:3000"

    links:
      - mongo

    volumes:
      - .:/home/api

  mongo:
    image: mongo

    ports:
      - "27017:27017"

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    volumes:
      - mongo:/data/db

volumes:
  mongo:
